### ISSUE TITLE
Add checkpointing to import of workspace ACLs

### ISSUE THREAD

**Issue by paulg-mscience** [databrickslabs/migrate#135]
For 90,000 notebooks, importing workspace ACLs takes 2+ hours when executed with `--num-parallel 32`. Sometimes the import workspace ACLs step fails with a transient http 500. Because there is no checkpointing, we are forced to reapply the ACLs to all 90,000 notebooks and wait another 2+ hours.

Here is the stack for the transient http 500 that we see sometimes:
```
Traceback (most recent call last):
  File "import_db.py", line 251, in <module>
    main()
  File "import_db.py", line 82, in main
    ws_c.import_workspace_acls(num_parallel=args.num_parallel)
  File "/home/ec2-user/github/databricks-migrate/dbclient/WorkspaceClient.py", line 564, in import_workspace_acls
    propagate_exceptions(futures)
  File "/home/ec2-user/github/databricks-migrate/threading_utils.py", line 3, in propagate_exceptions
    [future.result() for future in futures]
  File "/home/ec2-user/github/databricks-migrate/threading_utils.py", line 3, in <listcomp>
    [future.result() for future in futures]
  File "/home/ec2-user/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/ec2-user/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/ec2-user/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ec2-user/github/databricks-migrate/dbclient/WorkspaceClient.py", line 530, in apply_acl_on_object
    obj_status = self.get(WS_STATUS, {'path': obj_path})
  File "/home/ec2-user/github/databricks-migrate/dbclient/dbclient.py", line 195, in get
    raise Exception("Error: GET request failed with code {}\n{}".format(http_status_code, raw_results.text))
Exception: Error: GET request failed with code 500
{"error_code":"INTERNAL_ERROR","message":"Error handling request"}

```

**Comment by paulg-mscience** [comment]
@kevinkim9264 Any chance that you can add this checkpointing for us?

**Comment by kevinkim9264** [comment]
@paulg-mscience hey I have been really swamped. The checkpoint is part of this PR: https://github.com/databrickslabs/migrate/pull/152/files#diff-59c596132f0479f4fca02eec3de22f25f1703e25234d45000c987112e00a7b5aR557

Would be great if you could run testing or make use of it.

**Comment by paulg-mscience** [comment]
@kevinkim9264 I will test it next week. Thanks!

**Comment by paulg-mscience** [comment]
@kevinkim9264  I finally had a chance to give ACL import checkpointing a good test. All my tests were successful! My testing also included testing of inherited directory and notebook ACLs. As a bonus the change to not duplicated inherited ACLs made the ACL import much faster. Before it was taking 2+ hours to import ACLs for our 90,000 notebooks. Now it takes less than 15 mins! Thanks again.
