### ISSUE TITLE
Getting a 429 error when importing notebooks

### ISSUE THREAD

**Issue by petrcv-db** [databrickslabs/migrate#161]
I'm getting the following error when trying to import notebooks to a new workspace:
```
2022-04-11,13:43:41;DEBUG;Starting new HTTPS connection (4): xxx-play-ground.cloud.databricks.com:44
3
2022-04-11,13:43:41;WARNING;Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None
)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd36
b945730>: Failed to establish a new connection: [Errno 24] Too many open files')': /api/2.0/workspace/im
port
2022-04-11,13:43:41;DEBUG;Starting new HTTPS connection (4): xxx-play-ground.cloud.databricks.com:44
3
2022-04-11,13:43:41;DEBUG;https://xxx-play-ground.cloud.databricks.com:443 "POST /api/2.0/workspace/import HTTP/1.1" 400 None
2022-04-11,13:43:41;INFO;Error uploading file: /Development/Search/Visual-similarity/dev_autoencoder_image_similarity/data_processing/depricated/2_data_soft_labeling.dbc
2022-04-11,13:43:41;DEBUG;https://xxx-play-ground.cloud.databricks.com:443 "POST /api/2.0/workspace/import HTTP/1.1" 400 None
2022-04-11,13:43:41;INFO;Error uploading file: /Development/Search/Visual-similarity/dev_autoencoder_image_similarity/utils/0_functions.dbc
Traceback (most recent call last):
  File "migrate/migration_pipeline.py", line 328, in <module>
    main()
  File "migrate/migration_pipeline.py", line 324, in main
    pipeline.run()
  File "/home/ubuntu/migrate/pipeline/pipeline.py", line 64, in run
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/migrate/pipeline/pipeline.py", line 73, in _run_task
    task.run()
  File "/home/ubuntu/migrate/tasks/tasks.py", line 178, in run
    ws_c.import_all_workspace_items(archive_missing=self.args.archive_missing,
  File "/home/ubuntu/migrate/dbclient/WorkspaceClient.py", line 739, in import_all_workspace_items
    propagate_exceptions(futures)
  File "/home/ubuntu/migrate/threading_utils.py", line 3, in propagate_exceptions
    [future.result() for future in futures]
  File "/home/ubuntu/migrate/threading_utils.py", line 3, in <listcomp>
    [future.result() for future in futures]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/migrate/dbclient/WorkspaceClient.py", line 734, in _upload_all_files
    propagate_exceptions(futures)
  File "/home/ubuntu/migrate/threading_utils.py", line 3, in propagate_exceptions
    [future.result() for future in futures]
  File "/home/ubuntu/migrate/threading_utils.py", line 3, in <listcomp>
    [future.result() for future in futures]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/migrate/dbclient/WorkspaceClient.py", line 723, in _file_upload_helper
    resp_upload = self.post(WS_IMPORT, nb_input_args)
  File "/home/ubuntu/migrate/dbclient/dbclient.py", line 259, in post
    return self.http_req('post', endpoint, json_params, version, print_json, files_json)
  File "/home/ubuntu/migrate/dbclient/dbclient.py", line 243, in http_req
    raise Exception("Error: {0} request failed with code {1}\n{2}".format(http_type,
Exception: Error: post request failed with code 429
```
I tried decreasing the `--num-parallel` param to `10`, but still no luck. Any idea how to overcome this error?

**Comment by petrcv-db** [comment]
I tried setting `--retry-backoff 10 --retry-total 10` It seems like it runs a bit longer (not sure if it imports more notebooks) but then it fails with the same error

**Comment by paulg-mscience** [comment]
I have had success with importing 90,000 notebooks with these params:
```
--num-parallel 8 --use-checkpoint --debug --retry-total=30 --retry-backoff=1.0
```
I am running on AWS Linux EC2 m5.4xlarge with 16vCPU and 64GB.
Takes 1 hour 18 min to import.

**Comment by petrcv-db** [comment]
Awesome, with these param values I was finally able to import the notebooks. Thanks Paul!

**Comment by paulg-mscience** [comment]
@petrcv-db Nice!

**Comment by kevinkim9264** [comment]
Thank you. Updated the internal SOP. Will update the README too, or if anyone wants to contribute, that also works.
