### ISSUE TITLE
Clusters attached to pools failed to be imported

### ISSUE THREAD

**Issue by MullikaUser** [databrickslabs/migrate#171]
I ran into the following error when trying to run the import pipeline:
```
Traceback (most recent call last):
  File "migration_pipeline.py", line 328, in <module>
    main()
  File "migration_pipeline.py", line 324, in main
    pipeline.run()
  File "/Users/symp/migrate/pipeline/pipeline.py", line 64, in run
    future.result()
  File "/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/symp/migrate/pipeline/pipeline.py", line 73, in _run_task
    task.run()
  File "/Users/symp/migrate/tasks/tasks.py", line 227, in run
    cl_c.import_cluster_configs()
  File "/Users/symp/migrate/dbclient/ClustersClient.py", line 259, in import_cluster_configs
    new_cluster_conf = self.cleanup_cluster_pool_configs(cluster_conf, cluster_creator)
  File "/Users/symp/migrate/dbclient/ClustersClient.py", line 68, in cleanup_cluster_pool_configs
    cluster_json['instance_pool_id'] = pool_id_dict[old_pool_id]
TypeError: 'NoneType' object is not subscriptable
```

I have figured out that this will happen when you are trying to import the clusters, which in the old workspace, were previously attached to pools.

The root cause is, in the source code, you've built a pipeline with the steps of importing clusters prior to importing instance pools. So when you're trying to recreate clusters using pools, there were no pools ready to be attached to.

**migration_pipeline.py**
```
def build_import_pipeline(client_config, checkpoint_service, args) -> Pipeline:
    """
    All import jobs
    import_instance_profiles -> import_users -> import_groups -> import_secrets -> import_clusters -> import_instance_pools -> import_jobs
                                                              -> log_workspace_items -> import_notebooks -> import_workspace_acls
                                                              -> import_metastore -> import_metastore_table_acls
    """
    skip_tasks = args.skip_tasks

    source_info_file = os.path.join(client_config['export_dir'], "source_info.txt")
    with open(source_info_file, 'r') as f:
        source_url = f.readline()
        confirm = input(f"Import from `{source_url}` into `{client_config['url']}`? (y/N) ")
        if confirm.lower() not in ["y", "yes"]:
            raise RuntimeError("User aborted import pipeline. Exiting..")

    completed_pipeline_steps = checkpoint_service.get_checkpoint_key_set(
        wmconstants.WM_IMPORT, wmconstants.MIGRATION_PIPELINE_OBJECT_TYPE)
    pipeline = Pipeline(client_config['export_dir'], completed_pipeline_steps, args.dry_run)
    import_instance_profiles = pipeline.add_task(InstanceProfileImportTask(client_config, checkpoint_service, wmconstants.INSTANCE_PROFILES in skip_tasks))
    import_users = pipeline.add_task(UserImportTask(client_config, checkpoint_service, wmconstants.USERS in skip_tasks), [import_instance_profiles])
    import_groups = pipeline.add_task(GroupImportTask(client_config, checkpoint_service, wmconstants.GROUPS in skip_tasks), [import_users])
    import_notebooks = pipeline.add_task(NotebookImportTask(client_config, checkpoint_service, args, wmconstants.NOTEBOOKS in skip_tasks), [import_groups])
    import_workspace_acls = pipeline.add_task(WorkspaceACLImportTask(client_config, checkpoint_service, wmconstants.WORKSPACE_ACLS in skip_tasks), [import_notebooks])
    import_secrets = pipeline.add_task(SecretImportTask(client_config, checkpoint_service, wmconstants.SECRETS in skip_tasks), [import_groups])
    >> HERE >> import_instance_pools = pipeline.add_task(InstancePoolsImportTask(client_config, args, checkpoint_service, wmconstants.INSTANCE_POOLS in skip_tasks), [import_secrets])
    >> HERE >> import_clusters = pipeline.add_task(ClustersImportTask(client_config, args, checkpoint_service, wmconstants.CLUSTERS in skip_tasks), [import_instance_pools])
    import_jobs = pipeline.add_task(JobsImportTask(client_config, args, checkpoint_service, wmconstants.JOBS in skip_tasks), [import_clusters])
    import_metastore = pipeline.add_task(MetastoreImportTask(client_config, checkpoint_service, args, wmconstants.METASTORE in skip_tasks), [import_groups])
    import_metastore_table_acls = pipeline.add_task(MetastoreTableACLImportTask(client_config, args, checkpoint_service, wmconstants.METASTORE_TABLE_ACLS in skip_tasks), [import_metastore])
    return pipeline
```

After swapping between these two steps, all should be fine. Not sure if this would help anyone facing the same issue.

PS. I only looked into and fixed part of code as there was an error about importing clusters/pools. If this change I made would possibly break any other parts of the migration pipeline, please let me know asap. Thanks a lot!

**Comment by mrchristine** [comment]
@kevinkim9264 can you have someone review this? It does look correct that we need the pools imported prior to clusters. CC: @gregwood-db if you can help with this change.

**Comment by kevinkim9264** [comment]
@mrchristine the change in the order would imply that instance_pools will be imported before cluster_policies are created. Do you think that would not cause other problems?

**Comment by mrchristine** [comment]
Yes, that's fine. Cluster policies reference fields via string values and doesn't verify that resources exist during creation. Creating the instance_pools first would work well and resolve this issue.
