### ISSUE TITLE
Error during import processing

### ISSUE THREAD

**Issue by atadogramaci** [databrickslabs/migrate#188]
Client is facing errors during import processing. It fails as below log. The below causes the migration to fail:

Command: python3 migration_pipeline.py --azure --profile dev3 --import-pipeline --use-checkpoint --session workspace_dev_test3

 

Get: [workspace_id_removed]/api/2.0/workspace/get-status

2022-07-05,21:17:43;INFO;ws-stat:

2022-07-05,21:17:43;INFO;Skipping inherited permissions..

2022-07-05,21:17:43;INFO;Working on ACL for path: [/Repos/[email_removed]

Get: [workspace_id_removed]/api/2.0/workspace/get-status

2022-07-05,21:17:43;WARNING;{"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Path ([/Repos/[email_removed]) doesn't exist."}

 

2022-07-05,21:17:43;ERROR;{"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Path ([/Repos/[email_removed]) doesn't exist.", "http_status_code": 404}

2022-07-05,21:17:43;INFO;Working on ACL for path: [/Repos/[email_removed]

Get: [workspace_id_removed]/api/2.0/workspace/get-status

2022-07-05,21:17:43;WARNING;{"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Path ([/Repos/email_removed]) doesn't exist."}

 

2022-07-05,21:17:43;ERROR;{"error_code": "RESOURCE_DOES_NOT_EXIST", "message": "Path ([/Repos/[email_removed]) doesn't exist.", "http_status_code": 404}

Traceback (most recent call last):

  File "migration_pipeline.py", line 328, in <module>

    main()

  File "migration_pipeline.py", line 324, in main

    pipeline.run()

  File "/root/databrick_migration/migrate-master/pipeline/pipeline.py", line 64, in run

    future.result()

  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result

    return self.__get_result()

  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result

    raise self._exception

  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/root/databrick_migration/migrate-master/pipeline/pipeline.py", line 73, in _run_task

    task.run()

  File "/root/databrick_migration/migrate-master/tasks/tasks.py", line 162, in run

    ws_c.import_workspace_acls(num_parallel=1)

  File "/root/databrick_migration/migrate-master/dbclient/WorkspaceClient.py", line 616, in import_workspace_acls

    propagate_exceptions(futures)

  File "/root/databrick_migration/migrate-master/threading_utils.py", line 3, in propagate_exceptions

    [future.result() for future in futures]

  File "/root/databrick_migration/migrate-master/threading_utils.py", line 3, in <listcomp>

    [future.result() for future in futures]

  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result

    return self.__get_result()

  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result

    raise self._exception

  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/root/databrick_migration/migrate-master/dbclient/WorkspaceClient.py", line 584, in apply_acl_on_object

    resp = self.patch(api_path, api_args)

  File "/root/databrick_migration/migrate-master/dbclient/dbclient.py", line 265, in patch

    return self.http_req('patch', endpoint, json_params, version, print_json)

  File "/root/databrick_migration/migrate-master/dbclient/dbclient.py", line 245, in http_req

    raw_results.text))

Exception: Error: patch request failed with code 500

{"error_code":"INTERNAL_ERROR","message":"Principal name not defined"}

**Comment by dougspadotto** [comment]
Even after skipping the workspace_acls task another occurence of "Principal name not defined" happened on cluster policies permissions calls:

put: https://<workspace-ommited>/api/2.0/permissions/cluster-policies/B962BFE05000001F
```

2022-08-17,20:36:50;DEBUG;[https://<workspace-ommited>:443](https://<workspace-ommited>/) "PUT /api/2.0/permissions/cluster-policies/B962BFE05000001F HTTP/1.1" 500 None

Traceback (most recent call last):

  File "[migration_pipeline.py](http://migration_pipeline.py/)", line 328, in <module>
    main()
  File "[migration_pipeline.py](http://migration_pipeline.py/)", line 324, in main
    [pipeline.run](http://pipeline.run/)()
  File "/[root/migrate/pipeline/pipeline.py](http://root/migrate/pipeline/pipeline.py)", line 64, in run
    future.result()
  File "/[usr/lib/python3.8/concurrent/futures/_base.py](http://usr/lib/python3.8/concurrent/futures/_base.py)", line 444, in result
    return self.__get_result()
  File "/[usr/lib/python3.8/concurrent/futures/_base.py](http://usr/lib/python3.8/concurrent/futures/_base.py)", line 389, in __get_result
    raise self._exception
  File "/[usr/lib/python3.8/concurrent/futures/thread.py](http://usr/lib/python3.8/concurrent/futures/thread.py)", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/[root/migrate/pipeline/pipeline.py](http://root/migrate/pipeline/pipeline.py)", line 73, in _run_task
    [task.run](http://task.run/)()
  File "/[root/migrate/tasks/tasks.py](http://root/migrate/tasks/tasks.py)", line 226, in run
    cl_c.import_cluster_policies()
  File "/[root/migrate/dbclient/ClustersClient.py](http://root/migrate/dbclient/ClustersClient.py)", line 412, in import_cluster_policies
    resp = self.put(api, acl_create_args)
  File "/[root/migrate/dbclient/dbclient.py](http://root/migrate/dbclient/dbclient.py)", line 262, in put
    return self.http_req('put', endpoint, json_params, version, print_json)
  File "/[root/migrate/dbclient/dbclient.py](http://root/migrate/dbclient/dbclient.py)", line 243, in http_req
    raise Exception("Error: {0} request failed with code {1}\n{2}".format(http_type,
Exception: Error: put request failed with code 500
{"error_code":"INTERNAL_ERROR","message":"Principal name not defined"}
```

**Comment by gregwood-db** [comment]
Just added proper support for Repos, and removed the Repo paths from the general directory logs to avoid this issue.
