### ISSUE TITLE
Getting KeyError: 'hipaa' while exporting hive metastore

### ISSUE THREAD

**Issue by WAG10** [databrickslabs/migrate#280]
Hi team,
I am using "python export_db.py --profile DEMO --metastore" command to export metastore, I know this is not being recommended but since I just want hive metastore alone to be exported so i went this way.
On running the above command i got below error:
cloudsa@VM:~/migrate$ python3 export_db.py --azure  --profile oldWS --metastore
Note: running export_db.py directly is not recommended. Please use migration_pipeline.py
Export the metastore configs at 2023-08-18 10:49:03.582725
Traceback (most recent call last):
  File "export_db.py", line 332, in <module>
    main()
  File "export_db.py", line 155, in main
    hive_c = HiveClient(client_config, checkpoint_service)
  File "/home/cloudsa/migrate/dbclient/HiveClient.py", line 20, in __init__
    super().__init__(configs, checkpoint_service)
  File "/home/cloudsa/migrate/dbclient/ClustersClient.py", line 16, in __init__
    self.hipaa = configs['hipaa']
KeyError: 'hipaa'
To correct this error i just commented the "hipaa" occurrence all over the code and then it worked fine.
Her i just wat to understand what the implication of this would be( as in what hipaa actually means here an what it does.)
Kind help would be highly appreciated.

**Comment by gregwood-db** [comment]
Fixed in https://github.com/databrickslabs/migrate/commit/0f744398a2ede104ab6c0fbd80dcf2b04e3c80f7
