### ISSUE TITLE
API_Metastore_Work_Leave_Me_Alone cluster creation is failing in Azure

### ISSUE THREAD

**Issue by johnlourdu** [databrickslabs/migrate#296]
We have accidently deleted on of our workspaces and worked with MSFT and recovered the workspace. I am attempting to export the recovered workspace in Azure, but API_Metastore_Work_Leave_Me_Alone cluster creation is failing due to below error. I believe this error is expected in Azure as the worker environment would have been removed for the deleted workspace. Is there any workaround and how to proceed further?

`python3 migration_pipeline.py --profile <source_profile> --export-pipeline --use-checkpoint --session 1003 --azure --retry-total 30 --num-parallel 8 --retry-backoff 1.0 --use-checkpoint`

`2024-01-09,13:44:47;WARNING;{"error_code": "BAD_REQUEST", "message": "Current organization 372068208196994 does not have any associated worker environments", "details": [{"@type": "type.googleapis.com/google.rpc.ErrorInfo", "reason": "CM_API_ERROR_SOURCE_CALLER_ERROR", "domain": ""}]}

Traceback (most recent call last):
  File "/Users/xxxxx/repos/migrate/migration_pipeline.py", line 378, in <module>
    main()
  File "/Users/xxxx/repos/migrate/migration_pipeline.py", line 374, in main
    pipeline.run()
  File "/Users/xxxx/repos/migrate/pipeline/pipeline.py", line 64, in run
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/xxxxx/repos/migrate/pipeline/pipeline.py", line 73, in _run_task
    task.run()
  File "/Users/xxxx/repos/migrate/tasks/tasks.py", line 377, in run
    secrets_c.log_all_secrets(cluster_name=self.args.cluster_name)
  File "/Users/xxxxx/repos/migrate/dbclient/SecretsClient.py", line 41, in log_all_secrets
    cid = self.start_cluster_by_name(cluster_name) if cluster_name else self.launch_cluster()
  File "/Users/xxxx/repos/migrate/dbclient/ClustersClient.py", line 558, in launch_cluster
    raise Exception("Could not launch cluster. Verify that the --azure or --gcp flag or cluster config is correct.")
Exception: Could not launch cluster. Verify that the --azure or --gcp flag or cluster config is correct.`

**Comment by snowch** [comment]
Did you find a workaround?  I'm also seeing this issue.

**Comment by mrchristine** [comment]
Can you provide a cluster instead of relying on the default cluster?

**Comment by snowch** [comment]
Do you mean with the `-cluster-name CLUSTER_NAME` parameter?

**Comment by mrchristine** [comment]
yes

**Comment by snowch** [comment]
The workspace we are migrating from was deleted and restored and I understand it isn't possible to start clusters on restored workspaces.

**Comment by mrchristine** [comment]
Given that the workspace was deleted and restored, it's read only and you won't be able to export the ACLs. Closing this out now.
