### ISSUE TITLE
Issue with tools using it for GCP imports: 

### ISSUE THREAD

**Issue by gobiviswanath** [databrickslabs/migrate#49]
got some updates from (who is leading Databricks-GCP migration efforts):

**1. Users/Groups - successfully migrated, but saw the command failed at the end:**

```
Importing group admins :
Traceback (most recent call last):
  File "import_db.py", line 219, in <module>
    main()
  File "import_db.py", line 41, in main
    scim_c.import_all_users_and_groups()
  File "/Users/pnaik/Source/Databricks_Migration/migrate/dbclient/ScimClient.py", line 437, in import_all_users_and_groups
    self.import_groups(group_dir)
  File "/Users/pnaik/Source/Databricks_Migration/migrate/dbclient/ScimClient.py", line 403, in import_groups
    old_email = old_user_emails[m['value']]
KeyError: '100000'
```

**2. Notebook - download gave the below error:**

```
Downloading: /Conviva3D/DataManagement/BugsAndProblems/B&P-01-20160628-Cannot-Save-PbRl.scala
Get: https://conviva.cloud.databricks.com/api/2.0/workspace/export
Downloading: /Conviva3D/DataManagement/BugsAndProblems/Clone of B&P-01-20160628-Cannot-Save-PbRl.scala
Get: https://conviva.cloud.databricks.com/api/2.0/workspace/export
Traceback (most recent call last):
  File "export_db.py", line 297, in <module>
    main()
  File "export_db.py", line 81, in main
    num_notebooks = ws_c.download_notebooks()
  File "/Users/pnaik/Source/Databricks_Migration/migrate/dbclient/WorkspaceClient.py", line 229, in download_notebooks
    dl_resp = self.download_notebook_helper(notebook_path, export_dir=self.get_export_dir() + ws_dir)
  File "/Users/pnaik/Source/Databricks_Migration/migrate/dbclient/WorkspaceClient.py", line 256, in download_notebook_helper
    save_filename = save_path + os.path.basename(notebook_path) + '.' + resp.get('file_type')
TypeError: can only concatenate str (not "NoneType") to str
```

Looks like API response parsing needs a tuning in https://github.com/databrickslabs/migrate/blob/master/dbclient/WorkspaceClient.py @mwc

**Comment by mrchristine** [comment]
Re 1: The mapping would fail if the user did not `--reset-export` from a previous run. The missing key error indicates there was a mismatch of the lookup table. 

Re 2: It's unclear where the export is failing. Can you check the export response for the notebook you reported? 
The only place you can get `None` is from the export response, which should provide a `file_type` attribute for us to determine the type of notebook exported. If this returns `None` and we did export the notebook, then this is a bug on Databricks and you would need to file a support issue against them.
