### ISSUE TITLE
while importing cluster from source to target databricks workspace, I am getting ACL KeyError.

### ISSUE THREAD

**Issue by jugalashar** [databrickslabs/migrate#63]
I am exporting a Standard databricks azure cluster to another Standard databricks azure cluster. I am getting the below error:
Traceback (most recent call last):
  File "import_db.py", line 219, in <module>
    main()
  File "import_db.py", line 97, in main
    cl_c.import_cluster_configs()
  File "/home//migrate/dbclient/ClustersClient.py", line 269, in import_cluster_configs
    acl_args = {'access_control_list' : self.build_acl_args(data['access_control_list'])}
KeyError: 'access_control_list'

ACL_clusters.log file showed the following error:
{"error_code": "INTERNAL_ERROR", "message": "FEATURE_DISABLED: ACLs for cluster are disabled or not available in this tier", "http_status_code": 500}

Is there a way to import without ACL?

**Comment by mrchristine** [comment]
Not today, we'll have to add this capability in the future.

**Comment by akdm-volastra** [comment]
Plus one on this

**Comment by kishoresmeda** [comment]
After 1.5yrs on this enhancement, still looking for the feature.

Any update will be helpful @gregwood-db @mrchristine

**Comment by SqrtPapere** [comment]
Any news or workaround? Neither my workspaces have ACL or the ability to set it up (not Premium SKU)

**Comment by gregwood-db** [comment]
Just out of curiosity, does skipping the `WORKSPACE_ACLS` and `METASTORE_TABLE_ACLS` tasks fix this issue? Handling the error message for `FEATURE_DISABLED` is easy, but handling the empty objects for ACLs down the pipeline will take a little more work. I suppose we could add a `--skip-acls` flag to make that easier.

**Comment by SqrtPapere** [comment]
Yes it did, I tried it a few hours ago but i wasn't sure that all went ok afterwards... looks alright now, everything is moved correctly to the new workspace.
